spring.datasource.url=jdbc:postgresql://localhost:5432/math_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
# This allows Flyway to manage your tables
spring.flyway.enabled=true


